### ISSUE TITLE
Dúvidas sobre o projeto "Blaze"

### ISSUE THREAD

**Issue by Patrikr7** [viniciusgdr/Blaze#3]
Curti demais seu código, tenho duas dúvidas:
1º Percebi que rodando na opção "double" por algumas vezes para de rodar do nada tendo que reiniciar o processo, é normal esse comportamento?

2º Como fazer para subir a aplicação no servidor e deixar ele rodando? Tentei utilizar o "pm2" mas sem sucesso, como prosseguir essa etapa?

Vlwsss e parabéns pelo código.

**Comment by CrimsonSunrise** [comment]
Olá @Patrikr7!
Aproveitei a pergunta pra dar minha opinião sobre o projeto do Vinicius e como fiz pra subir num servidor.
Eu já tive problemas parecidos com outros websockets onde o mesmo parava e tinha que reiniciar manualmente mas não é o caso com o do Vinicius, comigo o double rodou tranquilo, tanto na minha máquina quanto no servidor.
Talvez seria interessante debugar pra ter uma ideia.

Provavelmente rodar num servidor não vai ter problema algum.

Eu usei uma EC2 da AWS pra manter o código rodando 24/7 e salvando os resultados num bando de dados.
Nativamente as instâncias Linux da AWS não rodam node mas o próprio site de ajuda da AWS tem um tutorial de como instalar.

Você pode encontrar o tutorial [https://docs.aws.amazon.com/pt_br/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html](neste link).

**Comment by viniciusgdr** [comment]
> 

Opa amigo, talvez a conexão possa cair por meio que sua internet esteja ruim. Testei aqui e durou mais que 5 horas.

**Comment by viniciusgdr** [comment]
> > 
> 
> Opa amigo, talvez a conexão possa cair por meio que sua internet esteja ruim. Testei aqui e durou mais que 5 horas.

você pode usar o evento 'closed' e conseguir re-conectar o socket implementando você mesmo

**Comment by CrimsonSunrise** [comment]
Há algumas semanas eu tive um erro parecido, agora que me lembro, onde desconectou algumas vezes e eu fiz uma função no close mesmo pra reconectar. Nos últimos dias tenho tido desconexões e mesmo com a função pra reconectar não reconecta. Provavelmente algum tipo de bloqueio por ip temporário. Pensei em montar um request com python direto na API pra ver como se comporta mas ainda não fiz. Uma boa oportunidade se quiser tentar @Patrikr7 .
