### ISSUE TITLE
Alguma sugestão de implementação após as mudanças recentes na Blaze?

### ISSUE THREAD

**Issue by brandaolopes** [viniciusgdr/Blaze#35]
Primeiramente gostaria de agradecer pelo seu código. Tenho usado em alguns projetos pessoais tanto pro double como pro crash. 

Recentemente a Blaze implementou algumas mudanças que impactaram no funcionamento de qualquer aplicação que usa seu código como base para a conexão do websocket. Acredito que eles possam ter mudado as URLs das conexões ou algo assim. Vocês teriam alguma sugestão para contornar esse problema?

**Comment by viniciusgdr** [comment]
Aparentemente foi apenas a URL. irei homologar e subo as alterações. Perdão pela demora, não costumo ler mensagens na Github

**Comment by viniciusgdr** [comment]
Resolvido.

**Comment by mslvance** [comment]
Olá. 

Após essa mudança de plataforma da Blaze, algo foi alterado? Minha aplicação parou de funcionar às 7h40 de hoje.

**Comment by viniciusgdr** [comment]
Sim, as urls foram trocadas.
