### ISSUE TITLE
Há como acessar o token dinamicamente?

### ISSUE THREAD

**Issue by vinilouz** [viniciusgdr/Blaze#4]
Primeiramente parabéns pelo código, esta me ajudando muito para automatizar o processo de entradas que faço.
Mas criando uma interface para a:

const socket = makeConnectionBlaze({
    token: string
})

Penso um colocar e-mail e senha e ter esse acesso, eu que não vi alguma função que faça isso? Ou poderia me guiar para como achar esse dado?

**Comment by viniciusgdr** [comment]
o token você pode conseguir através das requisições feitas no site da blaze
![Screenshot_1](https://user-images.githubusercontent.com/79378773/184995951-6afe7031-c271-45a8-9b50-c74d89e8acef.png)

**Comment by jeffersonveloso** [comment]
> Primeiramente parabéns pelo código, esta me ajudando muito para automatizar o processo de entradas que faço. Mas criando uma interface para a:
> 
> const socket = makeConnectionBlaze({ token: string })
> 
> Penso um colocar e-mail e senha e ter esse acesso, eu que não vi alguma função que faça isso? Ou poderia me guiar para como achar esse dado?

Vc pode criar uma ferramenta de webscraping para capturar o token da conta ou pegar no localStorage da blaze.

Estou disposto a criar uma ferramenta com estratégias para gerar sinais para uma ferramenta que vai jogar de forma automática. Já faço isso coletando sinais de grupo do telegram mas gostaria de criar algo moldado para minimizar loss e com diferentes estratégias. Se alguém animar me chame aqui nesse post.

**Comment by CrimsonSunrise** [comment]
> > Primeiramente parabéns pelo código, esta me ajudando muito para automatizar o processo de entradas que faço. Mas criando uma interface para a:
> > const socket = makeConnectionBlaze({ token: string })
> > Penso um colocar e-mail e senha e ter esse acesso, eu que não vi alguma função que faça isso? Ou poderia me guiar para como achar esse dado?
> 
> Vc pode criar uma ferramenta de webscraping para capturar o token da conta ou pegar no localStorage da blaze.
> 
> Estou disposto a criar uma ferramenta com estratégias para gerar sinais para uma ferramenta que vai jogar de forma automática. Já faço isso coletando sinais de grupo do telegram mas gostaria de criar algo moldado para minimizar loss e com diferentes estratégias. Se alguém animar me chame aqui nesse post.

Interessante ideia. Põe um email pra contato no seu perfil do github, fica mais fácil pra alguém entrar me contato.

**Comment by vinilouz** [comment]
> > Primeiramente parabéns pelo código, esta me ajudando muito para automatizar o processo de entradas que faço. Mas criando uma interface para a:
> > const socket = makeConnectionBlaze({ token: string })
> > Penso um colocar e-mail e senha e ter esse acesso, eu que não vi alguma função que faça isso? Ou poderia me guiar para como achar esse dado?
> 
> Vc pode criar uma ferramenta de webscraping para capturar o token da conta ou pegar no localStorage da blaze.
> 
> Estou disposto a criar uma ferramenta com estratégias para gerar sinais para uma ferramenta que vai jogar de forma automática. Já faço isso coletando sinais de grupo do telegram mas gostaria de criar algo moldado para minimizar loss e com diferentes estratégias. Se alguém animar me chame aqui nesse post.

Eu consegui criar uma forma de fazer isso e meu robo ficou totalmente funcional no momento, mas não acredito que meus sinais estejam bons o suficiente no momento. Caso queiram fazer parte do projeto podem me chamar no telegram: https://t.me/vinilouz
